# Site settings
title: In the Zone with Nathan Ahlstrom
index_title: In the Zone with Nathan Ahlstrom
header-img: img/cropped-starbirth-hubble-11.png
email: your-email@yourdomain.com
copyright_name: Nathan Ahlstrom
description: "Writing about Open Source Software, Web Development, and Life!"
baseurl: ""
url: "http://nathanahlstrom.com"
twitter_username: NathanAhlstrom
github_username:  NathanAhlstrom
email_username:  nathan@nathanahlstrom.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
excerpt_separator: <!--more-->

gems: [jekyll-paginate, jekyll-feed]
